# Generated by Django 4.2.2 on 2025-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
